project: 
  type: website
  output-dir: docs
  
website: 
  navbar: 
    left: 
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projectpage.qmd
      
format:
  html: 
    theme: Cerulean