project: 
  type: website
  output-dir: docs
  
website: 
  title: "My Site"
  navbar: 
    left: 
      - text: "About"
        href: intro.qmd
      - text: "Projects"
        href: projectpage.qmd
      - text: "Certifications"
        href: certifications.qmd
      
format:
  html: 
    theme: 
      - Morph
      - style.scss